data:
  train_dir: /scratch/project_2013256/lempio/hoa_out_speech_shards/train
  val_dir: /scratch/project_2013256/lempio/hoa_out_speech_shards/test_single_source
env:
  audio_loader: soundfile  # 'torchaudio' or 'soundfile'
  use_tqdm: false  # true for tqdm, false for print
io:
  checkpoint_dir: ./data-ddp/checkpoints
  generator_samples_dir: ./data-ddp/generator_samples
  val_samples_dir: ./data-ddp/val_samples
  log_dir: ./data-ddp/logs
model:
  in_channels: 4
training:
  max_steps: 50000
  pretrain_mel_steps: 0 #0 is default
  train_batch_size: 16
  val_batch_size: 4
  train_num_workers: 8
  val_num_workers: 2
  pin_memory: true
  lr: 2e-4
  mel_loss_coeff: 45.0
  mrd_loss_coeff: 1.0
  bandwidth: 6.6
  commit_loss_coeff: 1000
  spatial_loss_coeff: 1
  spatial_loss_every: 1
  val_every: 5000
  save_every: 5000
  sample_every: 5000
  max_checkpoints: 5
  device: cuda
